# Generated by Django 6.0.2 on 2026-02-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruckentech_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
