"""
Django settings for bruckentech project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# load environment variables from .env in project root
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-38s0-%jnu@0a0^cuqk$2s(t^zv93m-1aqdy6_pcj%3f^3gkjz&'  # fallback for dev only
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,bruckentech-ug.onrender.com').split(',')

# Strip whitespace from allowed hosts (important for comma-separated values)
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bruckentech_app',  # our application containing templates and views
    'markdownx',            # markdown editor for admin
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bruckentech.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bruckentech.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Account details shown in the "Account Details" page. Configure these via
# environment variables (or override here for development).
# In production we will raise an error if any required field is missing so the
# deploy fails fast instead of showing placeholder values.
ACCOUNT_DETAILS = {
    'bank': {
        'bank_name': os.getenv('BANK_NAME', 'Example Bank'),
        'account_name': os.getenv('BANK_ACCOUNT_NAME', 'Bruckentech Foundation'),
        'account_number': os.getenv('BANK_ACCOUNT_NUMBER', '0000000000'),
    },
    'mobile_money': {
        'provider': os.getenv('MM_PROVIDER', 'MTN Mobile Money'),
        'number': os.getenv('MM_NUMBER', '+256700000000'),
        'account_name': os.getenv('MM_ACCOUNT_NAME', 'Bruckentech Foundation'),
    }
}

# Temporary: disable strict production validation so local commands and
# migrations can run without requiring live account environment variables.
# Re-enable this check when you're ready to enforce real account details
# by uncommenting the block below.
#
# if not DEBUG:
#     from django.core.exceptions import ImproperlyConfigured
#
#     for section, fields in ACCOUNT_DETAILS.items():
#         for key, value in fields.items():
#             if not value:
#                 raise ImproperlyConfigured(
#                     f"Missing environment variable for account detail: {section}.{key}"
#                 )

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# additional locations for user‑defined static assets
STATICFILES_DIRS = [
    BASE_DIR / 'bruckentech_app' / 'static',
]

# Use WhiteNoise to serve static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (user-uploaded)
# Development: serve from local filesystem. In production you should replace
# this configuration with a cloud storage backend such as S3, and set an
# appropriate `DEFAULT_FILE_STORAGE` (e.g. `storages.backends.s3boto3.S3Boto3Storage`).
# The following defaults here will work for local development and staging but
# do not scale with multiple servers.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# optionally use S3 for media in production when USE_S3 env var set
if not DEBUG and os.getenv('USE_S3', 'False').lower() in ('true', '1', 'yes'):
    # django-storages will be required; install via requirements.txt
    INSTALLED_APPS.append('storages')
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', '')
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN', None)

    # validate that required credentials are present
    missing = [name for name in (
        'AWS_ACCESS_KEY_ID',
        'AWS_SECRET_ACCESS_KEY',
        'AWS_STORAGE_BUCKET_NAME',
    ) if not globals().get(name)]
    if missing:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            f"Missing AWS env vars for S3 storage: {', '.join(missing)}"
        )
